-- Phase 2 instrumented badge additions.
-- Additive only: lightweight durable usage storage plus new canonical badge definitions.

create table if not exists public.user_feature_usage (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  feature_key text not null,
  source text not null default 'unknown',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone not null default now()
);

create index if not exists idx_user_feature_usage_user_feature_created
  on public.user_feature_usage (user_id, feature_key, created_at desc);

create index if not exists idx_user_feature_usage_feature_created
  on public.user_feature_usage (feature_key, created_at desc);

alter table public.user_feature_usage enable row level security;

grant select on public.user_feature_usage to authenticated;

drop policy if exists user_feature_usage_read_own on public.user_feature_usage;
create policy user_feature_usage_read_own
  on public.user_feature_usage
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

insert into public.badge_definitions (
  id,
  name,
  description,
  icon,
  category,
  metric_key,
  target_value,
  sort_order,
  is_active,
  is_hidden
)
values
  ('importer', 'Importer', 'Import your first decklist', '📥', 'onboarding', 'import_deck_count', 1, 15, true, false),
  ('brewer', 'Brewer', 'Create 5 manual decks from scratch', '🧪', 'deckbuilding', 'manual_deck_count', 5, 25, true, false),
  ('idea_spark', 'Idea Spark', 'Use Turn my idea into a deck once', '💡', 'deckbuilding', 'idea_to_deck_usage_count', 1, 65, true, false),
  ('commander_picker', 'Commander Picker', 'Use Help me choose a commander 3 times', '👑', 'tools', 'commander_picker_usage_count', 3, 75, true, false),
  ('card_whisperer', 'Card Whisperer', 'Use Build around a card 5 times', '🎯', 'deckbuilding', 'build_around_card_usage_count', 5, 85, true, false),
  ('traders_eye', 'Trader''s Eye', 'Use Price Tracker 10 times', '📈', 'tools', 'price_tracker_lookup_count', 10, 95, true, false)
on conflict (id) do update
set
  name = excluded.name,
  description = excluded.description,
  icon = excluded.icon,
  category = excluded.category,
  metric_key = excluded.metric_key,
  target_value = excluded.target_value,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  is_hidden = excluded.is_hidden,
  updated_at = now();
