services:
  - type: web
    name: mtg-ai-assistant-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    pythonVersion: 3.10.13
    envVars:
      - key: OPENAI_API_KEY
        sync: false
