#!/usr/bin/env npx tsx
/**
 * Generate SQL INSERT statements for precon_decks from Westly/CommanderPrecons.
 * Run: npx tsx scripts/generate-precon-sql.ts
 * Output: precon_decks_all.sql (or stdout with --stdout)
 *
 * Uses the same parsing + Scryfall enrichment as POST /api/admin/precons/sync.
 */

import fs from "fs";
import path from "path";
import { fetchWestlyPreconRows } from "../lib/precons-westly-sync";

function escapeSql(str: string) {
  if (str == null || str === "") return "''";
  return "'" + String(str).replace(/'/g, "''").replace(/\\/g, "\\\\") + "'";
}

function escapeSqlArray(arr: string[]) {
  if (!Array.isArray(arr) || arr.length === 0) return "'{}'";
  const escaped = arr.map((c) => escapeSql(c)).join(",");
  return `ARRAY[${escaped}]::text[]`;
}

function sqlReleaseYear(y: number | null): string {
  if (y == null || Number.isNaN(y)) return "NULL";
  return String(y);
}

function sqlReleaseDate(d: string | null): string {
  if (d == null || d === "") return "NULL";
  const iso = String(d).trim().slice(0, 10);
  return `${escapeSql(iso)}::date`;
}

async function main() {
  const args = process.argv.slice(2);
  const stdout = args.includes("--stdout");
  const limit = args.find((a) => a.startsWith("--limit="));
  const maxRows = limit ? parseInt(limit.split("=")[1], 10) : 999_999;

  console.error("Fetching Westly/CommanderPrecons + Scryfall enrichment...");
  const { rows, fileErrors, scryfallMatched } = await fetchWestlyPreconRows();
  const slice = rows.slice(0, maxRows);

  console.error(
    `Parsed ${rows.length} precons (${fileErrors} file errors). Scryfall matched ${scryfallMatched}. Using ${slice.length} rows for SQL.`
  );

  const sqlLines = [
    "-- Generated by scripts/generate-precon-sql.ts",
    "-- Source: https://github.com/Westly/CommanderPrecons",
    "-- Run in Supabase SQL Editor (after migration 103_precon_decks_release_year_nullable_release_date.sql)",
    "",
    "INSERT INTO public.precon_decks (name, commander, colors, format, deck_text, set_name, release_year, release_date)",
    "VALUES",
  ];

  const values: string[] = [];
  for (const precon of slice) {
    if (!precon.deck_text?.trim()) continue;
    const dt = precon.deck_text;
    const tag = "p" + Math.random().toString(36).slice(2, 10);
    const colorsSql = escapeSqlArray(precon.colors || []);
    values.push(
      `  (${escapeSql(precon.name)}, ${escapeSql(precon.commander)}, ${colorsSql}, ${escapeSql(precon.format)}, $${tag}$${dt}$${tag}$, ${escapeSql(precon.set_name)}, ${sqlReleaseYear(precon.release_year)}, ${sqlReleaseDate(precon.release_date)})`
    );
  }

  sqlLines.push(values.join(",\n") + ";");
  sqlLines.push("");
  sqlLines.push(`-- ${values.length} precons in this file.`);
  sqlLines.push("-- To avoid duplicates, run: DELETE FROM precon_decks; before re-importing.");

  const sql = sqlLines.join("\n");

  if (stdout) {
    process.stdout.write(sql);
  } else {
    const outPath = path.join(process.cwd(), "precon_decks_all.sql");
    fs.writeFileSync(outPath, sql, "utf8");
    console.error(`\nWrote ${values.length} precons to ${outPath}`);
    console.error("Run this SQL in Supabase Dashboard → SQL Editor");
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
