export type AdminRisk = "low" | "medium" | "high" | "critical";
export type AdminCategory = "AI" | "App" | "Data" | "Money" | "SEO" | "Ops" | "Safety";

export type AdminRouteMeta = {
  path: string;
  methods: string[];
  category: AdminCategory;
  risk: AdminRisk;
  authRequired: boolean;
  writes: boolean;
  description: string;
  healthCheck?: "safe-get" | "skip-write" | "skip-dynamic";
  confirmationPhrase?: string;
  lastTouched?: string;
};

export const ADMIN_ROUTE_CATALOG: AdminRouteMeta[] = [
  {
    path: "/api/admin/audit",
    methods: ["GET"],
    category: "Safety",
    risk: "medium",
    authRequired: true,
    writes: false,
    description: "Recent admin audit log rows.",
    healthCheck: "safe-get",
  },
  {
    path: "/api/admin/audit-pinboard",
    methods: ["GET"],
    category: "Ops",
    risk: "low",
    authRequired: true,
    writes: false,
    description: "Ops pinboard summary for errors, spending, snapshots, and rate limits.",
    healthCheck: "safe-get",
  },
  {
    path: "/api/admin/route-health",
    methods: ["GET"],
    category: "Safety",
    risk: "low",
    authRequired: true,
    writes: false,
    description: "Admin route catalog and safe health probes.",
    healthCheck: "safe-get",
  },
  {
    path: "/api/admin/live-smoke",
    methods: ["GET", "POST"],
    category: "AI",
    risk: "medium",
    authRequired: true,
    writes: true,
    description: "Runs and stores the live chat/API smoke report.",
    healthCheck: "safe-get",
    confirmationPhrase: "RUN",
  },
  {
    path: "/api/admin/ai/health",
    methods: ["GET"],
    category: "AI",
    risk: "low",
    authRequired: true,
    writes: false,
    description: "OpenAI key/probe health.",
    healthCheck: "safe-get",
  },
  {
    path: "/api/admin/ai/model-config",
    methods: ["GET", "POST"],
    category: "AI",
    risk: "medium",
    authRequired: true,
    writes: true,
    description: "AI model routing and tier configuration.",
    healthCheck: "safe-get",
  },
  {
    path: "/api/admin/ai-usage/summary?days=7&limit=200",
    methods: ["GET"],
    category: "AI",
    risk: "low",
    authRequired: true,
    writes: false,
    description: "Website AI usage/cost summary.",
    healthCheck: "safe-get",
  },
  {
    path: "/api/admin/ai-usage-app/overview?days=7",
    methods: ["GET"],
    category: "App",
    risk: "low",
    authRequired: true,
    writes: false,
    description: "Mobile app AI usage dashboard overview.",
    healthCheck: "safe-get",
  },
  {
    path: "/api/admin/ai-usage-app/requests?days=3&limit=20",
    methods: ["GET"],
    category: "App",
    risk: "low",
    authRequired: true,
    writes: false,
    description: "Recent mobile app AI usage rows.",
    healthCheck: "safe-get",
  },
  {
    path: "/api/admin/app-ai-feedback",
    methods: ["GET"],
    category: "App",
    risk: "low",
    authRequired: true,
    writes: false,
    description: "Mobile app AI feedback reports.",
    healthCheck: "safe-get",
  },
  {
    path: "/api/admin/feedback-dashboard",
    methods: ["GET"],
    category: "App",
    risk: "low",
    authRequired: true,
    writes: false,
    description: "Website feedback dashboard data.",
    healthCheck: "safe-get",
  },
  {
    path: "/api/admin/errors",
    methods: ["GET"],
    category: "Safety",
    risk: "low",
    authRequired: true,
    writes: false,
    description: "Recent server/client error log rows.",
    healthCheck: "safe-get",
  },
  {
    path: "/api/admin/rate-limits",
    methods: ["GET"],
    category: "Safety",
    risk: "low",
    authRequired: true,
    writes: false,
    description: "Rate-limit diagnostics.",
    healthCheck: "safe-get",
  },
  {
    path: "/api/admin/config",
    methods: ["GET", "POST"],
    category: "Ops",
    risk: "high",
    authRequired: true,
    writes: true,
    description: "App config reads/writes; powers feature flags and ops toggles.",
    healthCheck: "safe-get",
  },
  {
    path: "/api/admin/cron/run",
    methods: ["POST"],
    category: "Ops",
    risk: "high",
    authRequired: true,
    writes: true,
    description: "Manual runner for selected production cron jobs.",
    healthCheck: "skip-write",
    confirmationPhrase: "RUN",
  },
  {
    path: "/api/admin/ops-reports/run",
    methods: ["POST"],
    category: "Ops",
    risk: "medium",
    authRequired: true,
    writes: true,
    description: "Manual daily/weekly ops report generation.",
    healthCheck: "skip-write",
    confirmationPhrase: "RUN",
  },
  {
    path: "/api/admin/ops-reports/list?limit=5",
    methods: ["GET"],
    category: "Ops",
    risk: "low",
    authRequired: true,
    writes: false,
    description: "Recent ops reports.",
    healthCheck: "safe-get",
  },
  {
    path: "/api/admin/ops/rollback-snapshot",
    methods: ["POST"],
    category: "Safety",
    risk: "critical",
    authRequired: true,
    writes: true,
    description: "Rollback price snapshot date to yesterday.",
    healthCheck: "skip-write",
    confirmationPhrase: "ROLLBACK",
  },
  {
    path: "/api/admin/price/snapshot/build",
    methods: ["POST"],
    category: "Data",
    risk: "high",
    authRequired: true,
    writes: true,
    description: "Build price snapshots from current deck card names.",
    healthCheck: "skip-write",
    confirmationPhrase: "RUN",
  },
  {
    path: "/api/admin/price/snapshot/bulk",
    methods: ["POST"],
    category: "Data",
    risk: "high",
    authRequired: true,
    writes: true,
    description: "Bulk Scryfall price snapshot import.",
    healthCheck: "skip-write",
    confirmationPhrase: "RUN",
  },
  {
    path: "/api/admin/data/table-sizes",
    methods: ["GET"],
    category: "Data",
    risk: "low",
    authRequired: true,
    writes: false,
    description: "Database table size overview.",
    healthCheck: "safe-get",
  },
  {
    path: "/api/admin/data/scryfall-cache-health",
    methods: ["GET"],
    category: "Data",
    risk: "low",
    authRequired: true,
    writes: false,
    description: "Scryfall cache health and gaps.",
    healthCheck: "safe-get",
  },
  {
    path: "/api/admin/data/cleanup-snapshots",
    methods: ["POST"],
    category: "Data",
    risk: "high",
    authRequired: true,
    writes: true,
    description: "Deletes old snapshot data.",
    healthCheck: "skip-write",
    confirmationPhrase: "DELETE",
  },
  {
    path: "/api/admin/data/cleanup-audit-logs",
    methods: ["POST"],
    category: "Safety",
    risk: "high",
    authRequired: true,
    writes: true,
    description: "Deletes old audit/error rows.",
    healthCheck: "skip-write",
    confirmationPhrase: "DELETE",
  },
  {
    path: "/api/admin/data/cleanup-abandoned-accounts",
    methods: ["POST"],
    category: "Safety",
    risk: "critical",
    authRequired: true,
    writes: true,
    description: "Deletes abandoned account data.",
    healthCheck: "skip-write",
    confirmationPhrase: "DELETE",
  },
  {
    path: "/api/admin/data/optimize-scryfall-cache",
    methods: ["POST"],
    category: "Data",
    risk: "medium",
    authRequired: true,
    writes: true,
    description: "Runs cache optimization/maintenance.",
    healthCheck: "skip-write",
    confirmationPhrase: "RUN",
  },
  {
    path: "/api/admin/data/vacuum-analyze",
    methods: ["POST"],
    category: "Data",
    risk: "medium",
    authRequired: true,
    writes: true,
    description: "Runs vacuum/analyze maintenance.",
    healthCheck: "skip-write",
    confirmationPhrase: "RUN",
  },
  {
    path: "/api/admin/precons",
    methods: ["GET"],
    category: "Data",
    risk: "low",
    authRequired: true,
    writes: false,
    description: "Precon browser/admin data.",
    healthCheck: "safe-get",
  },
  {
    path: "/api/admin/precons/sync",
    methods: ["POST"],
    category: "Data",
    risk: "high",
    authRequired: true,
    writes: true,
    description: "Replaces precon deck data from upstream source.",
    healthCheck: "skip-write",
    confirmationPhrase: "SYNC",
  },
  {
    path: "/api/admin/stripe/subscribers",
    methods: ["GET"],
    category: "Money",
    risk: "medium",
    authRequired: true,
    writes: false,
    description: "Stripe subscriber diagnostics.",
    healthCheck: "safe-get",
  },
  {
    path: "/api/admin/stripe/webhook-status",
    methods: ["GET"],
    category: "Money",
    risk: "low",
    authRequired: true,
    writes: false,
    description: "Stripe webhook health.",
    healthCheck: "safe-get",
  },
  {
    path: "/api/admin/stripe/sync-from-stripe",
    methods: ["POST"],
    category: "Money",
    risk: "critical",
    authRequired: true,
    writes: true,
    description: "Updates profile Pro status from live Stripe subscriptions.",
    healthCheck: "skip-write",
    confirmationPhrase: "SYNC STRIPE",
  },
  {
    path: "/api/admin/seo-pages/list",
    methods: ["GET"],
    category: "SEO",
    risk: "low",
    authRequired: true,
    writes: false,
    description: "Generated SEO page list.",
    healthCheck: "safe-get",
  },
  {
    path: "/api/admin/seo-pages/generate",
    methods: ["POST"],
    category: "SEO",
    risk: "medium",
    authRequired: true,
    writes: true,
    description: "Generates SEO page candidates.",
    healthCheck: "skip-write",
    confirmationPhrase: "RUN",
  },
  {
    path: "/api/admin/seo-pages/publish",
    methods: ["POST"],
    category: "SEO",
    risk: "high",
    authRequired: true,
    writes: true,
    description: "Publishes SEO pages.",
    healthCheck: "skip-write",
    confirmationPhrase: "PUBLISH",
  },
  {
    path: "/api/admin/indexnow/submit",
    methods: ["POST"],
    category: "SEO",
    risk: "medium",
    authRequired: true,
    writes: true,
    description: "Submits URLs to IndexNow.",
    healthCheck: "skip-write",
    confirmationPhrase: "SUBMIT",
  },
  {
    path: "/api/admin/backups",
    methods: ["GET"],
    category: "Safety",
    risk: "low",
    authRequired: true,
    writes: false,
    description: "Backup list/status.",
    healthCheck: "safe-get",
  },
  {
    path: "/api/admin/backups/create",
    methods: ["POST"],
    category: "Safety",
    risk: "high",
    authRequired: true,
    writes: true,
    description: "Creates a manual backup.",
    healthCheck: "skip-write",
    confirmationPhrase: "BACKUP",
  },
  {
    path: "/api/admin/backups/test-restore",
    methods: ["POST"],
    category: "Safety",
    risk: "critical",
    authRequired: true,
    writes: true,
    description: "Tests restore flow.",
    healthCheck: "skip-write",
    confirmationPhrase: "RESTORE TEST",
  },
  {
    path: "/api/admin/monitor",
    methods: ["GET"],
    category: "Ops",
    risk: "medium",
    authRequired: true,
    writes: true,
    description: "System monitor; can write audit alerts.",
    healthCheck: "safe-get",
  },
];

export const ADMIN_ROUTE_GROUPS: Record<AdminCategory, { title: string; routes: string[] }> = {
  AI: {
    title: "AI",
    routes: [
      "/admin/ai-health",
      "/admin/ai-usage",
      "/admin/ai-usage-app",
      "/admin/ai-reports",
      "/admin/app-ai-feedback",
      "/admin/route-health",
    ],
  },
  App: {
    title: "App",
    routes: [
      "/admin/app-whats-new",
      "/admin/app-scanner",
      "/admin/app-ai-feedback",
      "/admin/feedback-dashboard",
      "/admin/pro-gate",
    ],
  },
  Data: {
    title: "Data",
    routes: [
      "/admin/data",
      "/admin/datadashboard",
      "/admin/precons",
      "/admin/budget-swaps",
      "/admin/route-health",
    ],
  },
  Money: {
    title: "Money",
    routes: ["/admin/monetize", "/admin/pro-gate", "/admin/ai-usage", "/admin/ai-usage-app"],
  },
  SEO: {
    title: "SEO",
    routes: ["/admin/seo/pages", "/admin/analytics-seed", "/admin/blog"],
  },
  Ops: {
    title: "Ops",
    routes: ["/admin/JustForDavy/command-center", "/admin/ops", "/admin/route-health", "/admin/deploy"],
  },
  Safety: {
    title: "Safety",
    routes: ["/admin/security", "/admin/backups", "/admin/ops", "/admin/route-health"],
  },
};

export function routeRiskRank(risk: AdminRisk): number {
  if (risk === "critical") return 4;
  if (risk === "high") return 3;
  if (risk === "medium") return 2;
  return 1;
}
