name: Daily Price Snapshot

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch: {}

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Call snapshot endpoint
        run: |
          if [ -z "${{ secrets.CRON_URL }}" ]; then
            echo "CRON_URL is not set. Define it in repo secrets (e.g., https://your.app/api/cron/price/snapshot)." >&2
            exit 1
          fi
          URL="${{ secrets.CRON_URL }}"
          KEY="${{ secrets.CRON_KEY }}"
          if [ -n "$KEY" ]; then
            if echo "$URL" | grep -q '?' ; then URL="$URL&key=$KEY"; else URL="$URL?key=$KEY"; fi
          fi
          echo "Calling $URL"
          curl -fsSL "$URL"
