/**
 * Shared default blog entries used by /blog (fallback) and Admin Blog Manager (Import Defaults).
 * Keeps public blog and admin in sync.
 */
export type BlogEntryDefault = {
  slug: string;
  title: string;
  excerpt: string;
  date: string;
  author: string;
  category: string;
  readTime: string;
  gradient: string;
  icon: string;
  imageUrl?: string;
};

export const DEFAULT_BLOG_POSTS: BlogEntryDefault[] = [
  { slug: 'roast-my-deck', title: '🔥 Roast My Deck: Get Your Deck Roasted by AI (And Share It)', excerpt: 'Paste your decklist, pick your heat level, and let the AI roast your deck — then save and share a permanent link so your playgroup can see it.', date: '2026-03-15', author: 'ManaTap Team', category: 'Announcement', readTime: '5 min read', gradient: 'from-amber-600 via-orange-600 to-rose-600', icon: '🔥' },
  { slug: 'deck-building-upgrades-march-2025', title: '✨ New Deck Building Features: Finish This Deck, Build From Collection & Smarter AI', excerpt: 'AI now helps you complete partial decks, generate Commander decks from your collection with a preview step, and gives color-identity–compliant card suggestions with hover previews.', date: '2026-03-06', author: 'ManaTap Team', category: 'Announcement', readTime: '6 min read', gradient: 'from-purple-600 via-pink-600 to-rose-600', icon: '✨' },
  { slug: 'devlog-23-days-soft-launch', title: '🚀 Devlog: 23 Days Into Soft Launch', excerpt: "We're now 23 days into the soft launch of ManaTap.ai, and the project has already grown faster than we expected. What began as an early-access experiment is turning into a genuinely smarter, sharper deck-building assistant.", date: '2025-11-26', author: 'ManaTap Team', category: 'Announcement', readTime: '6 min read', gradient: 'from-orange-600 via-red-600 to-pink-600', icon: '🚀' },
  { slug: 'welcome-to-manatap-ai-soft-launch', title: '🎉 Welcome to ManaTap AI – Your MTG Deck Building Assistant is Here!', excerpt: "We're thrilled to officially launch ManaTap AI! After months of development and testing, we're opening the gates to help you build better Magic: The Gathering decks with the power of AI.", date: '2025-11-01', author: 'ManaTap Team', category: 'Announcement', readTime: '8 min read', gradient: 'from-blue-600 via-purple-600 to-pink-600', icon: '🎉' },
  { slug: 'budget-commander-100', title: 'Building Competitive EDH on $100: The Complete Guide', excerpt: 'Build powerful Commander decks on a budget with smart card choices. Learn where to save, where to splurge, and which commanders offer the best value.', date: '2025-10-28', author: 'ManaTap Team', category: 'Budget Building', readTime: '5 min read', gradient: 'from-emerald-600 via-green-600 to-teal-600', icon: '💰', imageUrl: 'https://cards.scryfall.io/art_crop/front/e/e/ee6e5a35-fe21-4dee-b0ef-a8f2841511ad.jpg?1764180059' },
  { slug: 'mana-curve-mastery', title: 'Mastering the Mana Curve: The Foundation of Winning Deck Construction', excerpt: 'Learn the 2-3-4 rule for Commander and avoid common curve mistakes. Build decks that flow smoothly from early game to victory.', date: '2025-10-28', author: 'ManaTap Team', category: 'Strategy', readTime: '4 min read', gradient: 'from-violet-600 via-purple-600 to-indigo-600', icon: '📊' },
  { slug: 'budget-edh-hidden-gems', title: 'Building Budget EDH: 5 Hidden Gems Under $1', excerpt: 'Discover powerful budget cards that punch above their weight class in Commander. Build competitive decks without breaking the bank.', date: '2025-10-18', author: 'ManaTap Team', category: 'Budget Building', readTime: '5 min read', gradient: 'from-amber-600 via-orange-600 to-rose-600', icon: '💎', imageUrl: 'https://cards.scryfall.io/art_crop/front/d/6/d6914dba-0d27-4055-ac34-b3ebf5802221.jpg?1600698439' },
  { slug: 'how-to-build-your-first-commander-deck', title: 'How to Build Your First Commander Deck (Beginner Friendly)', excerpt: 'A complete beginner-friendly guide to building your first Magic: The Gathering Commander deck. Learn deck structure, card selection, and essential strategies.', date: '2026-01-27', author: 'ManaTap Team', category: 'Commander', readTime: '8 min read', gradient: 'from-green-600 via-emerald-600 to-teal-600', icon: '🎯', imageUrl: 'https://cards.scryfall.io/art_crop/front/8/2/824b2d73-2151-4e5e-9f05-8f63e2bdcaa9.jpg?1730632010' },
  { slug: 'the-7-most-common-deckbuilding-mistakes', title: 'The 7 Most Common Deckbuilding Mistakes in MTG', excerpt: 'Avoid these 7 common mistakes when building Magic: The Gathering decks. Learn how to fix mana curves, ramp issues, and card selection problems.', date: '2026-01-27', author: 'ManaTap Team', category: 'Strategy', readTime: '6 min read', gradient: 'from-red-600 via-rose-600 to-pink-600', icon: '⚠️' },
  { slug: 'edh-land-count-what-the-community-actually-runs', title: 'EDH Land Count: What the Community Actually Runs', excerpt: "Data-driven analysis of optimal land counts in Commander decks. Learn how many lands to run based on your deck's strategy, ramp, and curve.", date: '2026-01-27', author: 'ManaTap Team', category: 'Strategy', readTime: '7 min read', gradient: 'from-blue-600 via-cyan-600 to-teal-600', icon: '🌍' },
  { slug: 'top-budget-staples-every-mtg-player-should-know-2025', title: 'Top Budget Staples Every MTG Player Should Know in 2026', excerpt: 'Discover the best budget Magic: The Gathering staples under $5 that every Commander player should own. Build competitive decks without breaking the bank.', date: '2026-01-27', author: 'ManaTap Team', category: 'Budget Building', readTime: '9 min read', gradient: 'from-yellow-600 via-amber-600 to-orange-600', icon: '💎', imageUrl: 'https://cards.scryfall.io/art_crop/front/d/f/dfb7c4b9-f2f4-4d4e-baf2-86551c8150fe.jpg?1702429366' },
  { slug: 'bug-fixes-and-improvements-january-2025', title: '🔧 Bug Fixes & Improvements: Making ManaTap More Reliable', excerpt: "We've been hard at work fixing bugs, improving the user experience, and making ManaTap AI more reliable. Here's what's new in our latest update.", date: '2026-01-27', author: 'ManaTap Team', category: 'Announcement', readTime: '5 min read', gradient: 'from-blue-600 via-cyan-600 to-teal-600', icon: '🔧', imageUrl: 'https://cards.scryfall.io/art_crop/front/c/8/c8817585-0d32-4d56-9142-0d29512e86a9.jpg?1598304029' },
  { slug: 'why-ai-can-help-with-mtg-deck-building', title: '🤖 Why AI Can Help With MTG Deck Building (And Where It Needs Work)', excerpt: "AI is transforming how we build Magic decks, but it's not perfect. Learn how AI can accelerate your deck building, what it struggles with, and how we're making it better.", date: '2026-01-15', author: 'ManaTap Team', category: 'Strategy', readTime: '8 min read', gradient: 'from-indigo-600 via-purple-600 to-pink-600', icon: '🤖', imageUrl: 'https://cards.scryfall.io/art_crop/front/9/c/9c0c61e3-9f3d-4e7f-9046-0ea336dd8a2d.jpg?1594735806' },
  { slug: 'how-manatap-ai-works', title: "How ManaTap's MTG AI Deck Builder Works", excerpt: 'A plain-English explanation (plus a technical deep dive) of how ManaTap analyzes MTG decks for legality, colour identity, balance, and synergy.', date: '2026-01-17', author: 'ManaTap Team', category: 'Strategy', readTime: '10 min read', gradient: 'from-blue-600 via-purple-600 to-pink-600', icon: '🔬', imageUrl: 'https://cards.scryfall.io/art_crop/front/c/8/c8817585-0d32-4d56-9142-0d29512e86a9.jpg?1598304029' },
];
