import type { WestlyPreconRow } from "@/lib/precons-westly-sync";

// Temporary official decklist supplement for sets not yet present in Westly/CommanderPrecons.
// Source: Wizards Marvel Super Heroes Commander decklists, published 2026-06-11.
function deckText(lines: string[]): string {
  return lines.join("\n");
}

export const SUPPLEMENTAL_PRECON_ROWS: WestlyPreconRow[] = [
  {
    name: "Avengers Assemble",
    commander: "Captain America, Team Leader",
    colors: ["U", "R", "W"],
    format: "Commander",
    set_name: "Marvel Super Heroes Commander",
    release_year: 2026,
    release_date: "2026-06-26",
    deck_text: deckText([
      "1 Captain America, Team Leader",
      "1 Ant-Man, Elusive Avenger",
      "1 Bastion Protector",
      "1 Black Widow, Agile Avenger",
      "1 Captain America, Living Legend",
      "1 Captain Marvel, Apex Avenger",
      "1 Captain Mar-Vell, Space-Born",
      "1 Director Nick Fury",
      "1 Falcon and Redwing",
      "1 Firebird, Blazing Ranger",
      "1 Hawkeye, Avenging Archer",
      "1 Hercules, Olympian Hero",
      "1 Iron Man, Armored Avenger",
      "1 Jarvis, Earth's Mightiest Butler",
      "1 Jocasta, Automaton Avenger",
      "1 Metallic Mimic",
      "1 Patriot, Shield Wielder",
      "1 Photon, Mighty Marvel",
      "1 Professor Hulk",
      "1 Quicksilver, Speedster",
      "1 Rescue, Pepper Potts",
      "1 Scarlet Witch, Chaotic Avenger",
      "1 Shang-Chi and the Ten Rings",
      "1 She-Hulk, Wallbreaker",
      "1 Speed, Young Avenger",
      "1 The Wasp, Winsome Avenger",
      "1 Thor, Asgard's Avenger",
      "1 Vision, Synthezoid Avenger",
      "1 War Machine, Avenging Arsenal",
      "1 Winter Soldier, Reborn Avenger",
      "1 Arcane Denial",
      "1 Destroy Evil",
      "1 Heroic Return",
      "1 Heroic Sacrifice",
      "1 Make Your Move",
      "1 Methods of the Mighty",
      "1 Swords to Plowshares",
      "1 Austere Command",
      "1 Avenge",
      "1 Dismantling Wave",
      "1 Raise the Palisade",
      "1 Rip Apart",
      "1 West Coast Expansion",
      "1 Folk Hero",
      "1 Gift of Immortality",
      "1 Kindred Discovery",
      "1 Love on the Battlefield",
      "1 Reconnaissance Mission",
      "1 Avengers Tower",
      "1 Clifftop Retreat",
      "1 Coastal Peak",
      "1 Command Tower",
      "1 Exotic Orchard",
      "1 Frostboil Snarl",
      "1 Furycalm Snarl",
      "1 Glacial Fortress",
      "1 Glittering Massif",
      "1 Irrigated Farmland",
      "1 Mystic Monastery",
      "1 Path of Ancestry",
      "1 Plaza of Heroes",
      "1 Port Town",
      "1 Prairie Stream",
      "1 Radiant Summit",
      "1 Scavenger Grounds",
      "1 Scorched Geyser",
      "1 Secluded Courtyard",
      "1 Spectator Seating",
      "1 Sulfur Falls",
      "1 Unclaimed Territory",
      "5 Island",
      "5 Mountain",
      "6 Plains",
      "1 Arcane Signet",
      "1 Avengers Quinjet",
      "1 Door of Destinies",
      "1 Fellwar Stone",
      "1 Herald's Horn",
      "1 Hero's Blade",
      "1 Hulkbuster Armor",
      "1 Relic of Legends",
      "1 Sol Ring",
      "1 Talisman of Conviction",
      "1 Talisman of Creativity",
      "1 Talisman of Progress",
      "1 Thought Vessel",
      "1 Tome of Legends",
    ]),
  },
  {
    name: "Wakanda Forever",
    commander: "T'Challa, the Black Panther",
    colors: ["G", "W"],
    format: "Commander",
    set_name: "Marvel Super Heroes Commander",
    release_year: 2026,
    release_date: "2026-06-26",
    deck_text: deckText([
      "1 T'Challa, the Black Panther",
      "1 Bast, Panther Goddess",
      "1 Birds of Paradise",
      "1 Dora Milaje Elite",
      "1 Everett K. Ross, Hapless Attache",
      "1 Fleecemane Lion",
      "1 Hatut Zeraze Strike Force",
      "1 Ingenious Smith",
      "1 Loyal Guardian",
      "1 Loyal Retainers",
      "1 M'Baku, Jabari Chieftain",
      "1 Metalwork Colossus",
      "1 Meteor Golem",
      "1 Nakia, Wakandan Operative",
      "1 Okoye, Mighty and Adored",
      "1 Palace Jailer",
      "1 Panther Robot",
      "1 Queen Mother Ramonda",
      "1 Shuri, the Black Panther",
      "1 Solemn Simulacrum",
      "1 Storm, Queen of Wakanda",
      "1 T'Chaka, Venerable King",
      "1 W'Kabi, Shield of the Nation",
      "1 Zuri, Warrior of Wakanda",
      "1 Beast Within",
      "1 Dispatch",
      "1 Fight for the Throne",
      "1 Generous Gift",
      "1 Valorous Stance",
      "1 Ancestral Communion",
      "1 Harmonize",
      "1 Martial Coup",
      "1 Nature's Lore",
      "1 Overwhelming Stampede",
      "1 Vanquish the Horde",
      "1 Wakanda Forever!",
      "1 Divine Visitation",
      "1 Greater Good",
      "1 Bountiful Promenade",
      "1 Canopy Vista",
      "1 Command Tower",
      "1 Evolving Wilds",
      "1 Fortified Village",
      "1 Path of Ancestry",
      "1 Razorverge Thicket",
      "1 Scattered Groves",
      "1 Scavenger Grounds",
      "1 Sungrass Prairie",
      "1 Sunpetal Grove",
      "1 Terramorphic Expanse",
      "1 The Great Mound",
      "1 Throne of the High City",
      "12 Forest",
      "12 Plains",
      "1 Arcane Signet",
      "1 Conduit of Worlds",
      "1 Coveted Jewel",
      "1 Gilded Lotus",
      "1 Hammer of Nazahn",
      "1 Heart-Shaped Herb",
      "1 Helm of the Host",
      "1 Kimoyo Beads",
      "1 King Solomon's Frogs",
      "1 Midnight Angel Armor",
      "1 Mind's Eye",
      "1 N'Yami-Class Mother Ship",
      "1 Panther Habit",
      "1 Royal Talon Fighter Jet",
      "1 Scourglass",
      "1 Shuri's Fabricator",
      "1 Sol Ring",
      "1 Sword of the Animist",
      "1 The Spear of Bashenga",
      "1 Thran Dynamo",
      "1 Trading Post",
      "1 Vibranium Mining Mech",
      "1 Vibranium Strike Gauntlets",
      "1 Whispersilk Cloak",
    ]),
  },
  {
    name: "The Fantastic Four",
    commander: "Invisible Woman",
    colors: ["W", "U", "R", "G"],
    format: "Commander",
    set_name: "Marvel Super Heroes Commander",
    release_year: 2026,
    release_date: "2026-06-26",
    deck_text: deckText([
      "1 Invisible Woman",
      "1 Alicia Masters, Skilled Sculptor",
      "1 Black Bolt, Inhuman King",
      "1 Council of Reeds",
      "1 Crystal, Inhuman Princess",
      "1 Dragon Man, Reformed Robot",
      "1 Franklin Richards, Ascendant",
      "1 Galactus, Devourer of Worlds",
      "1 H.E.R.B.I.E., Lovable Robot",
      "1 Human Torch",
      "1 Lockjaw, Slobbering Teleporter",
      "1 Medusa, Inhuman Queen",
      "1 Mister Fantastic",
      "1 Mister Fantastic, Reed Richards",
      "1 Namor, Atlantean King",
      "1 Power Pack",
      "1 Silver Surfer, Galactus's Herald",
      "1 The Thing",
      "1 Valeria Richards, Precocious",
      "1 Willie Lumpkin, Postman",
      "1 Bovine Intervention",
      "1 Clever Concealment",
      "1 First Family",
      "1 Galvanic Iteration",
      "1 Invisible Force Field",
      "1 Path to Exile",
      "1 Cleansing Nova",
      "1 Collective Effort",
      "1 Cultivate",
      "1 Cut a Deal",
      "1 Deep Analysis",
      "1 Expressive Iteration",
      "1 Fantastic Elasticity",
      "1 Farseek",
      "1 Flame On!",
      "1 Genesis Ultimatum",
      "1 Hull Breach",
      "1 Into the Time Vortex",
      "1 It's Clobberin' Time!",
      "1 Nova Flame",
      "1 Promise of Loyalty",
      "1 Quantum Misalignment",
      "1 Recurring Insight",
      "1 Seize the Day",
      "1 Taunt from the Rampart",
      "1 Terramorph",
      "1 Three Visits",
      "1 Tragic Arrogance",
      "1 Ultimate Nullification",
      "1 Annie Joins Up",
      "1 Cosmic Crucible",
      "1 Mind's Dilation",
      "1 Monologue Tax",
      "1 Path of Discovery",
      "1 Whirlwind of Thought",
      "1 Baxter Building",
      "1 Canopy Vista",
      "1 Cinder Glade",
      "1 Clifftop Retreat",
      "1 Command Tower",
      "1 Evolving Wilds",
      "1 Exotic Orchard",
      "1 Fabled Passage",
      "1 Glacial Fortress",
      "1 Hinterland Harbor",
      "1 Path of Ancestry",
      "1 Prairie Stream",
      "1 Radiant Summit",
      "1 Rejuvenating Springs",
      "1 Rootbound Crag",
      "1 Scorched Geyser",
      "1 Sodden Verdure",
      "1 Sulfur Falls",
      "1 Sunpetal Grove",
      "1 Terramorphic Expanse",
      "3 Mountain",
      "4 Island",
      "5 Forest",
      "5 Plains",
      "1 Arcane Signet",
      "1 Chromatic Lantern",
      "1 Lightning Greaves",
      "1 Mirage Mirror",
      "1 Negative Zone Portal",
      "1 Sol Ring",
      "1 The Fantasticar",
      "1 Unstable Molecule Suit",
    ]),
  },
  {
    name: "Doom Prevails",
    commander: "Doctor Doom, King of Latveria",
    colors: ["U", "B", "R"],
    format: "Commander",
    set_name: "Marvel Super Heroes Commander",
    release_year: 2026,
    release_date: "2026-06-26",
    deck_text: deckText([
      "1 Doctor Doom, King of Latveria",
      "1 Abomination, World Ravager",
      "1 Baron Strucker, HYDRA Overlord",
      "1 Batroc the Leaper",
      "1 Chameleon, Master of Disguise",
      "1 Containment Construct",
      "1 Helmut Zemo, Mastermind",
      "1 Iron Monger, Sadistic Tycoon",
      "1 Kang Prime",
      "1 Kang, Temporal Tyrant",
      "1 Killmonger, Ruthless Usurper",
      "1 Klaw, Master of Sound",
      "1 Lady Loki, Agent of Chaos",
      "1 Living Laser",
      "1 Loki, the Deceiver",
      "1 Madame Hydra",
      "1 Molecule Man",
      "1 Moonstone, Harsh Mistress",
      "1 Prowler, Clawed Thief",
      "1 Puppet Master, String Puller",
      "1 Red Ghost, Intangible Genius",
      "1 Spark Double",
      "1 Stilt-Man, Towering Terror",
      "1 Superior Foes of Spider-Man",
      "1 The Frightful Four",
      "1 The Squadron Sinister",
      "1 Titan of Littjara",
      "1 Titania, Proud Pummeler",
      "1 Tombstone, Career Criminal",
      "1 Tri-Sentinel, Act of Vengeance",
      "1 Typhoid Mary, Fractured",
      "1 Ultron, Unlimited",
      "1 Bedevil",
      "1 Chaos Warp",
      "1 Lethal Scheme",
      "1 Terminate",
      "1 Withering Torment",
      "1 Blasphemous Act",
      "1 Endless Ranks of HYDRA",
      "1 Extract Power",
      "1 Kindred Dominance",
      "1 Night's Whisper",
      "1 Syphon Mind",
      "1 Toxic Deluge",
      "1 Vandalblast",
      "1 Age of Ultron",
      "1 Archnemesis",
      "1 Black Market Connections",
      "1 Glorious Purpose",
      "1 Kang Dynasty",
      "1 Propaganda",
      "1 Canyon Slough",
      "1 Choked Estuary",
      "1 Coastal Peak",
      "1 Command Tower",
      "1 Crumbling Necropolis",
      "1 Dragonskull Summit",
      "1 Drowned Catacomb",
      "1 Exotic Orchard",
      "1 Fetid Pools",
      "1 Foreboding Ruins",
      "1 Frostboil Snarl",
      "1 Luxury Suite",
      "1 Path of Ancestry",
      "1 Scavenger Grounds",
      "1 Scorched Geyser",
      "1 Secluded Courtyard",
      "1 Smoldering Marsh",
      "1 Sulfur Falls",
      "1 Sunken Hollow",
      "1 Terramorphic Expanse",
      "1 Unclaimed Territory",
      "1 Villainous Hideout",
      "4 Island",
      "5 Mountain",
      "6 Swamp",
      "1 Arcane Signet",
      "1 Currency Converter",
      "1 Damocles Base, Sword of Kang",
      "1 Doom's Time Platform",
      "1 Loki's Scepter",
      "1 Patchwork Banner",
      "1 Progenitor's Icon",
      "1 Skullclamp",
      "1 Sol Ring",
      "1 Swiftfoot Boots",
      "1 Talisman of Dominance",
      "1 Talisman of Indulgence",
    ]),
  },
];
