name: lightweight-scryfall-import

on:
  schedule:
    - cron: "0 3 * * 0" # every Sunday at 03:00 UTC (1 hour after the other one)
  workflow_dispatch:

jobs:
  lightweight-import:
    runs-on: ubuntu-latest
    steps:
      - name: Validate secrets
        run: |
          echo "DEBUG: BASE_URL length: ${#BASE_URL}"
          echo "DEBUG: BASE_URL value: [$BASE_URL]"
          if [ -z "$BASE_URL" ]; then
            echo "Error: BASE_URL is not set in repo secrets." >&2
            exit 1
          fi
          if [ -z "$CRON_KEY" ]; then
            echo "Error: CRON_KEY is not set in repo secrets." >&2
            exit 1
          fi
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          CRON_KEY: ${{ secrets.CRON_KEY }}
      - name: Lightweight Scryfall import
        run: |
          set -e
          
          # Try the existing bulk endpoint with safe streaming parameters
          ENDPOINTS=(
            "$BASE_URL/api/cron/bulk-scryfall"
            "$BASE_URL/frontend/api/cron/bulk-scryfall"
          )
          
          SUCCESS=false
          
          for URL in "${ENDPOINTS[@]}"; do
            echo "DEBUG: Trying lightweight URL: [$URL]"
            echo "POST $URL"
            
            # First test the endpoint
            echo "Testing endpoint with streaming mode..."
            TEST_RESPONSE=$(curl -sS -w "\nHTTP_CODE:%{http_code}" \
              -X POST \
              -H "x-cron-key: $CRON_KEY" \
              -H "x-test-mode: true" \
              -H "x-use-streaming: true" \
              -H "Content-Type: application/json" \
              --max-time 30 \
              "$URL" 2>&1 || echo "CURL_ERROR")
            
            TEST_HTTP_CODE=$(echo "$TEST_RESPONSE" | grep "HTTP_CODE:" | cut -d: -f2 || echo "000")
            TEST_RESPONSE_BODY=$(echo "$TEST_RESPONSE" | sed '/HTTP_CODE:/d')
            
            echo "Test response code: $TEST_HTTP_CODE"
            echo "Test response body: $TEST_RESPONSE_BODY"
            
            if [ "$TEST_HTTP_CODE" -eq "200" ] || [ "$TEST_HTTP_CODE" -eq "201" ]; then
              echo "✅ Test successful! Starting streaming import..."
              
              # Single streaming request with safer parameters
              echo "Processing cards in streaming mode..."
              
              STREAM_RESPONSE=$(curl -sS -w "\nHTTP_CODE:%{http_code}" \
                -X POST \
                -H "x-cron-key: $CRON_KEY" \
                -H "x-use-streaming: true" \
                -H "Content-Type: application/json" \
                --max-time 300 \
                "$URL" 2>&1 || echo "CURL_ERROR")
              
              STREAM_HTTP_CODE=$(echo "$STREAM_RESPONSE" | grep "HTTP_CODE:" | cut -d: -f2 || echo "000")
              STREAM_RESPONSE_BODY=$(echo "$STREAM_RESPONSE" | sed '/HTTP_CODE:/d')
              
              echo "Streaming response code: $STREAM_HTTP_CODE"
              echo "Streaming response: $STREAM_RESPONSE_BODY"
              
              if [ "$STREAM_HTTP_CODE" -eq "200" ] || [ "$STREAM_HTTP_CODE" -eq "201" ]; then
                # Extract processing information
                CARDS_IMPORTED=$(echo "$STREAM_RESPONSE_BODY" | grep -o '"imported":[0-9]*' | cut -d: -f2 || echo "0")
                TOTAL_CARDS=$(echo "$STREAM_RESPONSE_BODY" | grep -o '"total_cards":[0-9]*' | cut -d: -f2 || echo "unknown")
                
                echo "✅ Streaming import completed successfully!"
                echo "📊 Cards imported: $CARDS_IMPORTED out of $TOTAL_CARDS total"
                SUCCESS=true
              else
                echo "❌ Streaming import failed with code: $STREAM_HTTP_CODE"
                echo "Response: $STREAM_RESPONSE_BODY"
              fi
              
              if [ "$SUCCESS" = true ]; then
                break
              fi
            elif [ "$TEST_HTTP_CODE" -eq "404" ]; then
              echo "❌ 404 Not Found - trying next endpoint"
            elif [ "$TEST_HTTP_CODE" -eq "401" ]; then
              echo "❌ 401 Unauthorized - check CRON_KEY secret"
              exit 1
            else
              echo "❌ Unexpected test response code: $TEST_HTTP_CODE"
              echo "Test response body: $TEST_RESPONSE_BODY"
            fi
          done
          
          if [ "$SUCCESS" = false ]; then
            echo "❌ All lightweight endpoints failed. Please check:"
            echo "   - BASE_URL secret points to correct domain"
            echo "   - Lightweight API routes are deployed correctly"
            echo "   - CRON_KEY secret is set correctly"
            exit 1
          fi
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          CRON_KEY: ${{ secrets.CRON_KEY }}